### ISSUE TITLE
-Werror=conversion build error in read_websocket()

### ISSUE THREAD

**Issue by krzk** [civetweb/civetweb#496]
When building 1.9.1 or latest master (d3c82e0537605a3ab6adf4474d1440e63b7ebef8):
```
| workspace/sources/civetweb/src/civetweb.c: In function 'read_websocket':
| workspace/sources/civetweb/src/civetweb.c:10909:16: error: conversion to 'size_t {aka unsigned int}' from 'long long unsigned int' may alter its value [-Werror=conversion]
|      data_len = (((uint64_t)ntohl(l1)) << 32) + ntohl(l2);
|                 ^
| cc1: all warnings being treated as errors
| src/CMakeFiles/c-library.dir/build.make:65: recipe for target 'src/CMakeFiles/c-library.dir/civetweb.c.o' failed
```

Building for armv7 under Yocto Poky 2.3 (arm-poky-linux-gnueabi-gcc  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a5).

gcc version 6.3.0 (GCC)

**Comment by bel2125** [comment]
This is a warning (you got and error due to the "-Werror" compile flag) that will not cause a problem in reality (see discussion for #488).

The -Werror flag in the CivetWeb CMake build is just set to ensure CivetWeb compiles on a high warning level without any warning. However, I do not get a warning for the same build (d3c82e0537605a3ab6adf4474d1440e63b7ebef8) on Travis ([build 1178](https://travis-ci.org/civetweb/civetweb/builds/257065856)) and AppVeyor ([build 1075](https://ci.appveyor.com/project/civetweb/civetweb/build/1075)). I have to take a closer look on the test environment, otherwise such warnings may again occur any time.

**Comment by bel2125** [comment]
I'm not sure how to get the CMake on Travis CI really build 32 bit code. 
If anyone knows, please tell me in #497.

I tried to fix the warning, but I'm not sure if I fixed if for your particular data model.
By "data model" I mean the combination of data type sizes, also printed by civetweb with the -I parameter:
```sh
> gcc -m32 civetweb.c main.c ...
> ./civetweb -I
...
Data model: int:2/4/4/8, float:4/8/12, char:1/4, ptr:4, size:4, time:4

> gcc -m64 civetweb.c main.c ...
> ./civetweb -I
...
Data model: int:2/4/8/8, float:4/8/16, char:1/4, ptr:8, size:8, time:8
```

Could you check if this warning is gone?

**Comment by krzk** [comment]
Unfortunately latest commit does not fix everything. Building f3de87ad6129b907c98a4faf8ebc3f318dcfbce9 causes:
```
src/civetweb.c:11009:40: error: conversion to 'size_t {aka unsigned int}' from 'uint64_t {aka long long unsigned int}' may alter its value [-Werror=conversion]
|                conn, mop, (char *)data, data_len, callback_data)) {
|                                         ^~~~~~~~
| cc1: all warnings being treated as errors
```
This is standard 32-bit ARM code so data model should be identical to -m32 on x86. To be precise, on the device this is printed (from v1.8):
```
CivetWeb V1.8
gcc: 6.3.0
Data model: i:2/4/4/8, f:4/8/8, c:1/4, p:4, s:4, t:4
```
Your -m32 compilation should trigger this error on this GCC. If you are using something different than GCC v6.3 (especially something older) then warning might not appear at all.

I did not look too much at Civetewb code but I assume that you are mixing operations between uint64 and types which are not fixed-length between platforms so the promotion appears for the operation itself and later result is being cast to shorter type for assignment.

The size_t and ssize_t types might vary in length... it can be even 16 bit (standard allows it). But anyway assuming that size_t is 64bit would be also a problem because only few 64-bit data models define unsigned integer as 64bit.

**Comment by bel2125** [comment]
Yes, some problems occur due to the mixing of fixed size and `size_t` data types, and this mixing is a constant annoyance for maintenance. There are even some `size_t` types in the API. Unfortunately it was like this before I took over CivetWeb, and API compatibility is a feature as well. However, I think it became a limiting factor for the future, so I created #498 to replace all `size_t` by a fixed 64 bit data type.

- I tested with GCC 5.4.0
- Travis CI used GCC 4.6.3, but I'm not sure if [this build](https://travis-ci.org/civetweb/civetweb/jobs/258971399) is really a 32 bit build. I'm not an expert on Travis and CMake, I got help for the initial setup of Travis + CMake, and I think I need help here to (see #497)

**Comment by bel2125** [comment]
I added a type cast that should fix the warning.
However, since Travis CI does not detect it, they may come back.
Travis uses a version from March 2012 (according to this [time line](https://gcc.gnu.org/releases.html)), but it seems one can install a newer one ([doc](https://docs.travis-ci.com/user/languages/cpp/)). I need to check this.

**Comment by krzk** [comment]
Commit f3f7ccc908acbd326ca34fb38bba2014272fee5f fixes last warning so now it compiles fine. Thanks!

**Comment by bel2125** [comment]
Thanks for your feedback. Unfortunately I did not manage to get a Travis CI test with GCC-6 running - it seems it does not work like written in the documentation. So a "GCC 6.x only" warning may come back without me noticing it in the first.

But for the moment - since all warnings are fixed, I will close this issue.
